### ISSUE TITLE
How to pass options to plugin?

### ISSUE THREAD

**Issue by Heiss** [grego/blades-plugins#1]
Hey,

i love the concept of blades, because hugo (my current goto static generator) lacks plugin system and does not play very well with other programming languages. I love the piping possibilities of blades. So i implement a kroki plugin (which was not possible with hugo as far as i know) on [my own](https://github.com/Heiss/blades-kroki). But this uses the default servers currently, which is not acceptable in my working environment (we try to host all services on our own). So it would be very beneficial, if you can specify the kroki server to use via the cli.

Something like this comes to my mind:

```bash
cat pages.json | blades-kroki --kroki-server https://kroki.my-institution.org
```

Can we implement something like this within the blades plugin system?

I think some grouping in toml would be practiable:
```toml
[plugins]
transform = ["blades-kroki"]

[plugins.blades-kroki]
kroki-server = "https://kroki.my-institution.org"
```

So blades looks up for all given transform plugins `["blades-kroki"]`, if there is any options given in the toml. Then it takes all keynames `kroki-server` and values `https://kroki.my-institution.org` and print it at the end of the given command `blades-kroki`. 

What do you think about it? This would make the plugin system more usable in favor of reuse already existing software like `coreutils` etc.

**Comment by grego** [comment]
This should already be possible:
```toml
[plugins]
transform = ["blades-kroki --kroki-server https://kroki.my-institution.org"]
```
